# Generated by Django 5.2.1 on 2025-06-25 08:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/user/profile/', verbose_name='Profile picture'),
        ),
    ]
