# Generated by Django 5.2.4 on 2025-08-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='quiz.quiz'),
        ),
    ]
