# Generated by Django 5.2.4 on 2025-08-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_resource_quiz'),
    ]

    operations = [
    ]
