# Generated by Django 5.2.4 on 2025-08-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_end_time_quiz_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='end_time',
        ),
    ]
