name: Deploy Django App with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Test Docker Compose build
      run: |
        echo "DJANGO_SECRET_KEY=dummy-for-tests" > .env  
        docker compose -f docker-compose.yaml build
        docker compose -f docker-compose.yaml run web python manage.py test
    
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd backend/
          
          # Pull latest changes
          git pull origin main
          
          # Build and start new containers
          sudo docker compose -f docker-compose.yaml up -d --build
          
          # Run migrations
          sudo docker compose -f docker-compose.yaml exec web python manage.py migrate
          
          # Collect static files
          sudo docker compose -f docker-compose.yaml exec web python manage.py collectstatic --noinput
          
          # If using nginx as reverse proxy
          sudo systemctl reload nginx